### ISSUE TITLE
Query to fetch all instances of a type also returns related types in `data`

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#302] opened 2018-09-17 09:10 UTC
As realized in https://github.com/cardstack/deck/pull/91#discussion_r217103524 , a query to fetch "all"  instances of some types returns not only instances of that type but those of the `defaultIncludes` ones, too.

For example, a call to `GET /api/documents?page%5Bsize%5D=1000` returns document-chapters in the `data` key, too, and `document-chapters` can be found in the `defaultIncludes` definition of the `document` type.

**Comment by bagby** [comment] 2018-10-26 05:18
The problem is that we are treating `type` as basically a keyword search, rather than forcing it to look for a specific content type. Some thing like #381 should fix it.

**Comment by bagby** [comment] 2018-10-31 03:32
Fixed by #381

**Closed** 2018-10-31 17:07 UTC
Labels: bug
