### ISSUE TITLE
Allow editing invisible attributes on cards

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#401] opened 2018-11-02 19:21 UTC
Some of the attributes of some card types are not supposed to be displayed on the isolated view. They are either supposed to be displayed on embedded view (e.g. `summary` for the document card), or used as meta information for the card. They should still have corresponding fields in the editor, and be marked accordingly. 
@ef4 mentioned that similar solution was provided for AIA and there fields were marked as "editorial". We can recreate implementation here.

**Comment by ef4** [comment] 2018-11-05 13:32
Right, this is a duplicate of https://github.com/cardstack/cardstack/issues/401

**Closed by ef4** 2018-11-05 13:32 UTC
